apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ai-sentiment-ingress
  namespace: ai-sentiment
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - aff6e2161278c48358fce5e1c81b4c0b-1776960371.us-west-2.elb.amazonaws.com
      secretName: tls-secret
  rules:
    - host: aff6e2161278c48358fce5e1c81b4c0b-1776960371.us-west-2.elb.amazonaws.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sentiment-svc
                port:
                  number: 80
