apiVersion: v1
kind: Service
metadata:
  name: sentiment-svc
  namespace: ai-sentiment
spec:
  selector:
    app: sentiment-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
